export const USER_ROLES = {
  VIEWER: "viewer",
  ANALYST: "analyst",
  ADMIN: "admin",
};

export const RECORD_TYPES = {
  INCOME: "income",
  EXPENSE: "expense",
};

export const USER_STATUS = {
  ACTIVE: true,
  INACTIVE: false,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard:read",

  RECORDS_READ: "records:read",
  RECORDS_CREATE: "records:create",
  RECORDS_UPDATE: "records:update",
  RECORDS_DELETE: "records:delete",

  USERS_READ: "users:read",
  USERS_READ_ONE: "users:readOne",
  USERS_UPDATE_ROLE: "users:updateRole",
  USERS_UPDATE_STATUS: "users:updateStatus",
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.VIEWER]: [
    PERMISSIONS.DASHBOARD_READ,
  ],

  [USER_ROLES.ANALYST]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.RECORDS_READ,
  ],

  [USER_ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_READ,

    PERMISSIONS.RECORDS_READ,
    PERMISSIONS.RECORDS_CREATE,
    PERMISSIONS.RECORDS_UPDATE,
    PERMISSIONS.RECORDS_DELETE,

    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_READ_ONE,
    PERMISSIONS.USERS_UPDATE_ROLE,
    PERMISSIONS.USERS_UPDATE_STATUS,
  ],
};